file_format: "1"
id: verdin
name: Verdin
type: shield
url: https://github.com/
requires: [pro_micro]
features:
  - keys
  - pointer
  - display
exposes:
  - i2c_glidepoint
siblings:
  - verdin_left
  - verdin_right


