file_format: "1"
id: cholibri
name: Cholibri
type: shield
url: https://github.com/
requires: [pro_micro]
features:
  - keys
  - pointer
  - display

exposes:
  - i2c_glidepoint
  - i2c_oled
  
siblings:
  - cholibri_left
  - cholibri_right


