file_format: "1"
id: cholibri
name: Cholibri
type: shield
url: https://github.com/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - i2c_glidepoint
siblings:
  - corne_left
  - corne_right
